In [1]:
import torch
import torch.nn as nn


In [11]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [12]:
neuron = nn.Linear(in_features=3, out_features=1)

In [13]:
output = neuron(inputs)

In [14]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [15]:
# verify

neuron.weight @ inputs + neuron.bias   # weighted function

tensor([1.5244], grad_fn=<AddBackward0>)

In [16]:
neuron.weight
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)