In [2]:
import numpy as np
import time

In [5]:
size = 10000000
py_list = list(range(size))
start = time.time()
sq = [x**2 for x in py_list]
end = time.time()
print(f"Python list time is: {end-start} sec")

np_list = np.array(py_list)
start = time.time()
sq = np_list ** 2
end = time.time()
print(f"numpy array time is: {end-start} sec")

Python list time is: 1.665764331817627 sec
numpy array time is: 0.2858116626739502 sec


In [8]:
arr = np.array([1, 2, 3,4])
print(arr)
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr2D)

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
a1 = np.zeros((3,4))
print(a1)

a2 = np.ones((3,4))
print(a2)

a3 = np.full((3,4), 44)
print(a3)
a3f = a3.astype(np.float64)
print(a3f)

a4 = np.eye(4)
print(a4)

a5 = np.linspace(1, 50, 5, dtype = int)
print(a5)

a6 = np.arange(1, 50, 2)
print(a6)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[44 44 44 44]
 [44 44 44 44]
 [44 44 44 44]]
[[44. 44. 44. 44.]
 [44. 44. 44. 44.]
 [44. 44. 44. 44.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1 13 25 37 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

arr2 = arr.reshape((3, 2))
print(arr2, arr2.shape)

print(arr.flatten())

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [33]:
#Indexing
print(arr[0])

print(arr[1][1])

#Fancy indexing
arrid = np.array([1, 2, 3, 4, 5])
idx = [0, 2, 3]
print(arrid[idx])

#Boolean indexing
print(arr[arr > 3])
print(arr[arr %2 == 0])

[1 2 3]
5
[1 3 4]
[4 5 6]
[2 4 6]


In [35]:
#slicing
arri = np.array([1, 2, 3, 4, 5])
print(arri[1:4])
s1 = arri[1:]
print(s1)
print(arri[:3])
print(arri[:])


[2 3 4]
[2 3 4 5]
[1 2 3]
[1 2 3 4 5]


In [36]:
#view is created
print(arri)
s1[1] = 200
print(arri)

[1 2 3 4 5]
[  1   2 200   4   5]


In [5]:
#multi-dimensional array

#2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(arr[1:3, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[[5]
 [8]]


In [10]:
#3D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, :, 1])
print(arr3D[:, 0, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
10
[[ 2  5]
 [ 8 11]]
[[1 2 3]
 [7 8 9]]


In [14]:
#vector normalization

arr = np.array([[2,3], [7,6]])
mean = np.mean(arr)
std = np.std(arr)
print(mean)
print(std)

normalized_arr = (arr-mean)/std
print(normalized_arr)

4.5
2.0615528128088303
[[-1.21267813 -0.72760688]
 [ 1.21267813  0.72760688]]
2.7755575615628914e-17
